sudo: required
services:
    - docker
language: python
env:
    - TOXENV=py26
    - TOXENV=py27
install: pip install tox
before_script:
    make start_couchdb 
script: tox
after_script:
    make stop_couchdb
