sudo: required
services:
    - docker
language: python
env:
    - TOXENV=py35
    - TOXENV=py34
    - TOXENV=py33
    - TOXENV=py32
install:
    - pip install tox
    - pip install -r requirements-docs.txt
before_script:
    make start_couchdb 
script:
    - tox
    - make docs
after_script:
    - make stop_couchdb
    - make clean_docs
after_success:
    coveralls
