sudo: required
services:
    - docker
language: python
env:
    - TOXENV=py35
install: pip install tox
before_script:
    make start_couchdb 
script: tox
after_script:
    make stop_couchdb
after_success:
    coveralls
